
CREATE OR REPLACE TABLE realestate.RATING (
        ID SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        RATING_TYPE VARCHAR(2000) NOT NULL
);

CREATE OR REPLACE TABLE realestate.SUBURB (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        SUBURB_NAME VARCHAR(1000) NOT NULL
);


CREATE OR REPLACE TABLE realestate.HOUSES (
        ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        OUR_ESTIMATED_PRICE MEDIUMINT NOT NULL,
        OWNERS_EXPECTED_PRICE MEDIUMINT NOT NULL,
        ACTUAL_SOLD_PRICE MEDIUMINT NOT NULL,
        LAST_BOUGHT_PRICE MEDIUMINT NOT NULL,
        YEARS_SINCE_LAST_BOUGHT INT NOT NULL,
        LISTING_WEB_LINK VARCHAR(5000) NOT NULL,
        BEDROOMS INT NOT NULL,
        STUDY BOOL NOT NULL,
        LIVING_AREAS INT NOT NULL,
        POOL BOOL NOT NULL,
        LAND_SIZE MEDIUMINT NOT NULL,
        RATING_ID SMALLINT NOT NULL,
        SUBURB_ID INT NOT NULL,
        CONSTRAINT `FK_SUBURB`
            FOREIGN KEY (SUBURB_ID) REFERENCES SUBURB (ID)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
        CONSTRAINT `FK_RATING`
            FOREIGN KEY (RATING_ID) REFERENCES RATING (ID)
            ON DELETE CASCADE
            ON UPDATE RESTRICT
);
